"use client";

import { FormEvent, useMemo, useState } from "react";

type Metric = { code: string; name: string; unit: string; limit: number; actual: number; trend: number[] };
const initialMetrics: Metric[] = [
  { code: "BI_NGHIEN", name: "Suất hao bi nghiền / than", unit: "g/tấn than", limit: 206.47, actual: 212.8, trend: [201, 205, 208, 212.8] },
  { code: "NH3", name: "Suất hao NH₃", unit: "g/kWh", limit: 0.8638, actual: 0.811, trend: [0.84, 0.86, 0.82, 0.811] },
  { code: "TUDUNG", name: "Tỷ lệ điện tự dùng", unit: "%", limit: 7.98, actual: 7.65, trend: [7.88, 7.73, 7.62, 7.65] },
  { code: "MO_BOITRON", name: "Suất hao mỡ bôi trơn bánh răng", unit: "g/kWh", limit: 0.0028, actual: 0.0031, trend: [0.0025, 0.0027, 0.0029, 0.0031] },
  { code: "NAOH", name: "Suất hao NaOH (30%)", unit: "g/kWh", limit: 0.0177, actual: 0.0159, trend: [0.016, 0.0164, 0.0161, 0.0159] },
  { code: "HCL", name: "Suất hao HCl (31%)", unit: "g/kWh", limit: 0.012, actual: 0.0126, trend: [0.0114, 0.0118, 0.0121, 0.0126] },
  { code: "PAC", name: "Suất hao PAC", unit: "g/kWh", limit: 0.0128, actual: 0.0119, trend: [0.0122, 0.0121, 0.012, 0.0119] },
];
function format(value: number, digits = 4) { return new Intl.NumberFormat("vi-VN", { maximumFractionDigits: digits }).format(value); }
function status(metric: Metric) { const variance = ((metric.actual - metric.limit) / metric.limit) * 100; return { variance, exceeded: metric.actual > metric.limit }; }

export default function Home() {
  const [metrics, setMetrics] = useState(initialMetrics);
  const [activeMetric, setActiveMetric] = useState(initialMetrics[0].code);
  const [actual, setActual] = useState(String(initialMetrics[0].actual));
  const [note, setNote] = useState("");
  const [saved, setSaved] = useState<string | null>(null);
  const selected = metrics.find((metric) => metric.code === activeMetric) ?? metrics[0];
  const overall = useMemo(() => { const exceeded = metrics.filter((metric) => status(metric).exceeded); return { exceeded, achieved: metrics.length - exceeded.length }; }, [metrics]);
  const chartData = metrics.map((metric) => ({ name: metric.name.replace("Suất hao ", "").replace("Tỷ lệ ", ""), variance: Number(status(metric).variance.toFixed(1)), exceeded: status(metric).exceeded }));
  function chooseMetric(code: string) { const metric = metrics.find((item) => item.code === code) ?? metrics[0]; setActiveMetric(code); setActual(String(metric.actual)); setSaved(null); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const value = Number(actual.replace(",", "."));
    if (!Number.isFinite(value) || value < 0) { setSaved("Giá trị nhập phải là số không âm."); return; }
    setMetrics(metrics.map((metric) => metric.code === activeMetric ? { ...metric, actual: value, trend: [...metric.trend.slice(-3), value] } : metric));
    try {
      const response = await fetch("/api/measurements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ metricCode: activeMetric, metricName: selected.name, period: "2026-08", actual: value, limitValue: selected.limit, note }) });
      setSaved(response.ok ? "Đã lưu số liệu và cập nhật cảnh báo." : "Đã cập nhật trên màn hình. Kho dữ liệu sẽ sẵn sàng sau khi triển khai.");
    } catch { setSaved("Đã cập nhật trên màn hình. Kho dữ liệu sẽ sẵn sàng sau khi triển khai."); }
  }
  return <main className="min-h-screen bg-[#edf3f4] text-[#15252a]">
    <header className="border-b border-[#cbd9dc] bg-[#123c47] px-5 py-4 text-white sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-[#e8ad3b] text-lg font-black text-[#123c47]">KT</div><div><p className="text-sm font-semibold tracking-wide">PXVH1</p><h1 className="text-lg font-bold">Quản lý chỉ tiêu kinh tế kỹ thuật</h1></div></div><div className="hidden items-center gap-2 text-sm text-[#d8e8e9] sm:flex"><span className="h-2 w-2 rounded-full bg-[#67d58b]" /> Kỳ theo dõi: Tháng 8/2026</div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-5 py-6 lg:grid-cols-[230px_1fr] lg:px-8">
      <aside className="rounded-xl border border-[#cbd9dc] bg-white p-3 shadow-sm lg:min-h-[680px]"><p className="px-3 pb-2 text-xs font-bold uppercase tracking-wider text-[#547177]">Chức năng</p><nav className="space-y-1 text-sm"><a className="flex items-center gap-3 rounded-lg bg-[#e3f0ef] px-3 py-2.5 font-semibold text-[#0f5960]" href="#dashboard">Tổng quan</a><a className="flex items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-slate-50" href="#nhap-lieu">Nhập số liệu</a><a className="flex items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-slate-50" href="#canh-bao">Cảnh báo</a><a className="flex items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-slate-50" href="#xu-huong">Xu hướng</a><a className="flex items-center gap-3 rounded-lg px-3 py-2.5 hover:bg-slate-50" href="#dinh-muc">Định mức</a></nav><div className="mt-8 rounded-lg bg-[#f4f7f7] p-3 text-xs leading-5 text-[#547177]">Cảnh báo được tính bằng cách so sánh giá trị thực tế với định mức từng chỉ tiêu.</div></aside>
      <section className="min-w-0 space-y-6" id="dashboard"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-[#0f737a]">Tổng quan vận hành</p><h2 className="text-2xl font-bold tracking-tight">Chỉ tiêu tháng 8/2026</h2></div><button onClick={() => document.getElementById("nhap-lieu")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex items-center gap-2 rounded-lg bg-[#e8ad3b] px-4 py-2.5 text-sm font-bold text-[#15252a] hover:bg-[#d99a26]">Nhập số liệu</button></div>
        <div className="grid gap-4 sm:grid-cols-3"><SummaryCard label="Chỉ tiêu đạt" value={`${overall.achieved}/${metrics.length}`} tone="ok" /><SummaryCard label="Vượt định mức" value={String(overall.exceeded.length)} tone="warn" /><SummaryCard label="Cần xác minh" value={overall.exceeded.length ? "Có" : "Không"} tone="info" /></div>
        <div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><section id="canh-bao" className="rounded-xl border border-[#cbd9dc] bg-white shadow-sm"><div className="border-b border-[#e3ebec] px-5 py-4"><h3 className="font-bold">Bảng cảnh báo chỉ tiêu</h3><p className="text-sm text-[#627d82]">Đỏ: vượt định mức. Xanh: đạt định mức.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-[#f4f7f7] text-xs uppercase tracking-wide text-[#547177]"><tr><th className="px-5 py-3">Chỉ tiêu</th><th className="px-3 py-3 text-right">Thực tế</th><th className="px-3 py-3 text-right">Định mức</th><th className="px-3 py-3 text-right">Chênh lệch</th><th className="px-5 py-3 text-right">Trạng thái</th></tr></thead><tbody>{metrics.map((metric) => { const result = status(metric); return <tr key={metric.code} className="border-t border-[#edf1f2]"><td className="px-5 py-3 font-medium"><span className="block">{metric.name}</span><span className="text-xs text-[#627d82]">{metric.unit}</span></td><td className="px-3 py-3 text-right font-semibold">{format(metric.actual)}</td><td className="px-3 py-3 text-right">{format(metric.limit)}</td><td className={`px-3 py-3 text-right font-semibold ${result.exceeded ? "text-[#c2473e]" : "text-[#16805c]"}`}>{result.variance > 0 ? "+" : ""}{format(result.variance, 1)}%</td><td className="px-5 py-3 text-right"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${result.exceeded ? "bg-[#fbe4df] text-[#b53c34]" : "bg-[#e1f4ea] text-[#127252]"}`}>{result.exceeded ? "Vượt" : "Đạt"}</span></td></tr>; })}</tbody></table></div></section>
          <section id="xu-huong" className="rounded-xl border border-[#cbd9dc] bg-white p-5 shadow-sm"><h3 className="font-bold">Chênh lệch so với định mức</h3><p className="mb-4 text-sm text-[#627d82]">Giá trị dương là vượt định mức</p><div className="space-y-3">{chartData.map((entry) => <div key={entry.name} className="grid grid-cols-[110px_1fr_52px] items-center gap-2 text-xs"><span className="truncate text-[#547177]" title={entry.name}>{entry.name}</span><div className="h-4 overflow-hidden rounded-full bg-[#e7eff0]"><div className={`h-full rounded-full ${entry.exceeded ? "bg-[#d66355]" : "bg-[#299b76]"}`} style={{ width: `${Math.min(Math.abs(entry.variance) * 6 + 8, 100)}%` }} /></div><span className={`text-right font-bold ${entry.exceeded ? "text-[#c2473e]" : "text-[#16805c]"}`}>{entry.variance > 0 ? "+" : ""}{format(entry.variance, 1)}%</span></div>)}</div></section></div>
        <section id="nhap-lieu" className="rounded-xl border border-[#cbd9dc] bg-white p-5 shadow-sm"><div className="mb-5"><p className="text-sm font-semibold text-[#0f737a]">Nhập trực tiếp</p><h3 className="text-xl font-bold">Ghi nhận số liệu chỉ tiêu</h3><p className="mt-1 text-sm text-[#627d82]">Sau khi lưu, hệ thống tự so sánh với định mức và đổi trạng thái cảnh báo.</p></div><form onSubmit={submit} className="grid gap-4 md:grid-cols-[1.5fr_0.75fr_1fr_auto]"><label className="grid gap-1.5 text-sm font-semibold">Chỉ tiêu<select value={activeMetric} onChange={(event) => chooseMetric(event.target.value)} className="rounded-lg border border-[#b9cbd0] bg-white px-3 py-2.5 font-normal outline-none focus:border-[#0f737a]">{metrics.map((metric) => <option key={metric.code} value={metric.code}>{metric.name}</option>)}</select></label><label className="grid gap-1.5 text-sm font-semibold">Thực tế <span className="font-normal text-[#627d82]">({selected.unit})</span><input value={actual} onChange={(event) => setActual(event.target.value)} inputMode="decimal" className="rounded-lg border border-[#b9cbd0] px-3 py-2.5 font-normal outline-none focus:border-[#0f737a]" /></label><label className="grid gap-1.5 text-sm font-semibold">Ghi chú<input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Ví dụ: vận hành tải thấp" className="rounded-lg border border-[#b9cbd0] px-3 py-2.5 font-normal outline-none focus:border-[#0f737a]" /></label><button className="mt-auto inline-flex h-[42px] items-center justify-center gap-2 rounded-lg bg-[#123c47] px-5 text-sm font-bold text-white hover:bg-[#0c303a]">Lưu số liệu</button></form>{saved && <p className="mt-4 rounded-lg bg-[#eef6f4] px-3 py-2 text-sm text-[#17684f]" role="status">{saved}</p>}</section>
        <section id="dinh-muc" className="rounded-xl border border-[#cbd9dc] bg-white p-5 shadow-sm"><h3 className="font-bold">Cơ sở cảnh báo phiên bản đầu</h3><p className="mt-2 text-sm leading-6 text-[#547177]">Các ngưỡng hiện được lấy từ sheet “Cảnh báo chỉ tiêu” trong sổ PXVH1: bi nghiền 206,47 g/tấn than; NH₃ 0,8638 g/kWh; điện tự dùng 7,98%; mỡ bôi trơn 0,0028 g/kWh; NaOH 0,0177 g/kWh; HCl 0,012 g/kWh và PAC 0,0128 g/kWh. Trước khi dùng chính thức, Phân xưởng cần xác nhận lại kỳ áp dụng và người phê duyệt cho từng định mức.</p></section>
      </section>
    </div>
  </main>;
}
function SummaryCard({ label, value, tone }: { label: string; value: string; tone: "ok" | "warn" | "info" }) { const styles = { ok: "border-l-[#299b76]", warn: "border-l-[#d66355]", info: "border-l-[#0f737a]" }; return <div className={`rounded-xl border border-[#cbd9dc] border-l-4 bg-white p-4 shadow-sm ${styles[tone]}`}><p className="text-sm font-semibold text-[#547177]">{label}</p><p className="mt-3 text-3xl font-bold tracking-tight">{value}</p></div>; }
