"use client";

import { useState, useMemo, useEffect } from "react";
import { Dialog as DialogPrimitive } from "radix-ui";
import {
  Copy,
  Check,
  Download,
  X,
  Mail,
  Edit3,
  RotateCcw,
  Sparkles,
  FileSpreadsheet,
} from "lucide-react";
import { CtktktDayEntries } from "@/lib/ctktkt-report";
import {
  extractCtktktEmailMetrics,
  generateEmailReportText,
  generateEmailReportHtml,
  CtktktEmailReportMetrics,
} from "@/lib/ctktkt-email-report";

interface CtktktEmailModalProps {
  isOpen: boolean;
  onClose: () => void;
  operatingDate: string; // YYYY-MM-DD
  currentEntries: CtktktDayEntries;
  previousEntries?: CtktktDayEntries;
  initialShiftName?: string;
}

const SHIFT_OPTIONS = ["Tổ C", "Tổ A", "Tổ B", "Tổ D"];

export function CtktktEmailModal({
  isOpen,
  onClose,
  operatingDate,
  currentEntries,
  previousEntries,
  initialShiftName = "Tổ C",
}: CtktktEmailModalProps) {
  const [shiftName, setShiftName] = useState(initialShiftName);
  const [copied, setCopied] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [customText, setCustomText] = useState<string | null>(null);
  const [gridReceivedMwh, setGridReceivedMwh] = useState<{ s1: number | null; s2: number | null }>({ s1: null, s2: null });

  useEffect(() => {
    if (!isOpen) return;
    const controller = new AbortController();
    fetch(`/api/daily-inputs?period=${operatingDate.slice(0, 7)}`, { cache: "no-store", signal: controller.signal })
      .then(async response => {
        if (!response.ok) throw new Error("Không đọc được điện nhận lưới.");
        return response.json() as Promise<{ entries?: Array<{ operatingDate: string; fieldCode: string; value: string }> }>;
      })
      .then(body => {
        const valueOf = (code: string) => {
          const value = Number(body.entries?.find(entry => entry.operatingDate === operatingDate && entry.fieldCode === code)?.value);
          return Number.isFinite(value) && value >= 0 ? value : null;
        };
        setGridReceivedMwh({ s1: valueOf("GRID_RECEIVE_S1"), s2: valueOf("GRID_RECEIVE_S2") });
      })
      .catch(error => {
        if (error instanceof DOMException && error.name === "AbortError") return;
        setGridReceivedMwh({ s1: null, s2: null });
      });
    return () => controller.abort();
  }, [isOpen, operatingDate]);

  // Trích xuất chỉ tiêu tự động từ dữ liệu CTKTKT
  const metrics: CtktktEmailReportMetrics = useMemo(() => {
    return extractCtktktEmailMetrics(currentEntries, previousEntries, {
      gridReceivedMwhS1: gridReceivedMwh.s1,
      gridReceivedMwhS2: gridReceivedMwh.s2,
    });
  }, [currentEntries, previousEntries, gridReceivedMwh]);

  // Sinh văn bản tự động
  const autoGeneratedText = useMemo(() => {
    return generateEmailReportText(metrics, shiftName);
  }, [metrics, shiftName]);

  const autoGeneratedHtml = useMemo(() => {
    return generateEmailReportHtml(metrics, shiftName);
  }, [metrics, shiftName]);

  // Văn bản hiển thị hiện tại (nếu người dùng đã tự sửa thì ưu tiên bản sửa)
  const currentText = customText !== null ? customText : autoGeneratedText;

  // Reset custom text khi đổi ngày hoặc đổi ca
  useEffect(() => {
    setCustomText(null);
    setIsEditing(false);
  }, [operatingDate, shiftName]);

  const formattedDateVn = useMemo(() => {
    return operatingDate.split("-").reverse().join("/");
  }, [operatingDate]);

  // Sao chép clipboard hỗ trợ cả HTML (cho Outlook/Gmail) lẫn Plain Text (cho Zalo/Notepad)
  const handleCopy = async () => {
    try {
      const textToCopy = currentText;
      // Nếu không sửa thì dùng HTML chuẩn phong cách Times New Roman, nếu sửa thì chuyển đoạn thành HTML tương ứng
      const htmlToCopy =
        customText === null
          ? autoGeneratedHtml
          : `<div style="font-family: 'Times New Roman', Times, serif; font-size: 13.5pt; line-height: 1.4; color: #000000; white-space: pre-wrap;">${customText
              .replace(/&/g, "&amp;")
              .replace(/</g, "&lt;")
              .replace(/>/g, "&gt;")}</div>`;

      if (typeof window !== "undefined" && navigator.clipboard && window.ClipboardItem) {
        const textBlob = new Blob([textToCopy], { type: "text/plain" });
        const htmlBlob = new Blob([htmlToCopy], { type: "text/html" });
        await navigator.clipboard.write([
          new ClipboardItem({
            "text/plain": textBlob,
            "text/html": htmlBlob,
          }),
        ]);
      } else if (navigator.clipboard) {
        await navigator.clipboard.writeText(textToCopy);
      }
      setCopied(true);
      setTimeout(() => setCopied(false), 3500);
    } catch {
      // Dự phòng nếu trình duyệt chặn ClipboardItem
      try {
        await navigator.clipboard.writeText(currentText);
        setCopied(true);
        setTimeout(() => setCopied(false), 3500);
      } catch {
        alert("Không thể tự động chép vào clipboard. Vui lòng chọn văn bản và nhấn Ctrl+C.");
      }
    }
  };

  // Tải về file text
  const handleDownloadTxt = () => {
    const blob = new Blob([currentText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Bao_cao_gui_mail_${operatingDate}_${shiftName.replace(/\s+/g, "_")}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DialogPrimitive.Root open={isOpen} onOpenChange={open => !open && onClose()}>
      <DialogPrimitive.Portal>
        <DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs animate-in fade-in" />
        <DialogPrimitive.Content className="fixed left-1/2 top-1/2 z-50 flex max-h-[92vh] w-[calc(100%-2rem)] max-w-4xl -translate-x-1/2 -translate-y-1/2 flex-col gap-0 overflow-hidden rounded-2xl border border-slate-300 bg-white shadow-2xl outline-none">
          {/* 1. Header Dialog */}
          <div className="flex items-center justify-between border-b border-slate-200 bg-slate-50/80 px-6 py-4">
            <div className="flex items-center gap-3">
              <div className="flex size-10 items-center justify-center rounded-xl bg-blue-600 text-white shadow-xs">
                <Mail className="size-5" />
              </div>
              <div>
                <DialogPrimitive.Title className="text-lg font-black text-[#173b64]">
                  Báo cáo gửi Mail hàng ngày (Kèm file CTKTKT)
                </DialogPrimitive.Title>
                <DialogPrimitive.Description className="text-xs text-slate-500">
                  Định dạng font Times New Roman chuẩn theo mẫu gửi Lãnh đạo Phân xưởng & Nhà máy · Ngày {formattedDateVn}
                </DialogPrimitive.Description>
              </div>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-200/80 hover:text-slate-700 transition-colors"
              title="Đóng"
            >
              <X className="size-5" />
            </button>
          </div>

          {/* 2. Thanh công cụ tùy chỉnh (Chọn Ca, Sửa, Chép, Tải) */}
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white px-6 py-3">
            {/* Chọn Ca / Tổ vận hành */}
            <div className="flex items-center gap-2 text-xs font-semibold text-slate-700">
              <span className="text-slate-500">Tổ trực vận hành:</span>
              <div className="flex rounded-lg border border-slate-200 bg-slate-100 p-0.5">
                {SHIFT_OPTIONS.map(opt => (
                  <button
                    key={opt}
                    type="button"
                    onClick={() => setShiftName(opt)}
                    className={`rounded-md px-2.5 py-1 text-xs font-bold transition-all ${
                      shiftName === opt
                        ? "bg-white text-blue-700 shadow-2xs"
                        : "text-slate-600 hover:text-slate-900"
                    }`}
                  >
                    {opt}
                  </button>
                ))}
              </div>
              <input
                type="text"
                value={shiftName}
                onChange={e => setShiftName(e.target.value)}
                placeholder="Tên tổ khác…"
                className="h-7 w-24 rounded border border-slate-200 px-2 text-xs font-semibold text-slate-800 outline-none focus:border-blue-500"
                title="Tự nhập tên tổ nếu khác"
              />
            </div>

            {/* Các nút tác vụ */}
            <div className="flex items-center gap-2">
              {customText !== null && (
                <button
                  type="button"
                  onClick={() => {
                    setCustomText(null);
                    setIsEditing(false);
                  }}
                  className="flex h-8 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100"
                  title="Khôi phục lại số liệu tự tính từ hệ thống"
                >
                  <RotateCcw className="size-3.5" />
                  Đặt lại số liệu gốc
                </button>
              )}

              <button
                type="button"
                onClick={() => setIsEditing(!isEditing)}
                className={`flex h-8 items-center gap-1.5 rounded-lg border px-2.5 text-xs font-bold transition-all ${
                  isEditing
                    ? "border-amber-300 bg-amber-50 text-amber-800"
                    : "border-slate-200 bg-white text-slate-700 hover:bg-slate-100"
                }`}
              >
                <Edit3 className="size-3.5" />
                {isEditing ? "Xem trước mẫu" : "Chỉnh sửa nội dung"}
              </button>

              <button
                type="button"
                onClick={handleDownloadTxt}
                className="flex h-8 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 text-xs font-bold text-slate-700 hover:bg-slate-100"
                title="Tải văn bản dạng file text"
              >
                <Download className="size-3.5" />
                Tải .txt
              </button>

              <button
                type="button"
                onClick={handleCopy}
                className={`flex h-8 items-center gap-1.5 rounded-lg px-3.5 text-xs font-bold text-white shadow-xs transition-all ${
                  copied
                    ? "bg-emerald-600 hover:bg-emerald-700"
                    : "bg-blue-600 hover:bg-blue-700 active:scale-95"
                }`}
              >
                {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
                {copied ? "Đã chép vào clipboard!" : "Sao chép gửi mail"}
              </button>
            </div>
          </div>

          {/* 3. Khung thông báo hỗ trợ người dùng */}
          <div className="flex items-center justify-between bg-blue-50/60 px-6 py-2 border-b border-blue-100 text-xs text-blue-900">
            <div className="flex items-center gap-2">
              <Sparkles className="size-4 text-blue-600 shrink-0" />
              <span>
                Khi bấm <strong>Sao chép gửi mail</strong>, nội dung đã được định dạng font <strong>Times New Roman</strong>. Bạn chỉ cần mở Outlook hoặc Gmail và nhấn <strong>Ctrl+V</strong> để dán trực tiếp.
              </span>
            </div>
            <div className="flex items-center gap-1.5 font-bold text-blue-700 shrink-0">
              <FileSpreadsheet className="size-3.5" />
              <span>Kèm file CTKTKT ngày {formattedDateVn}</span>
            </div>
          </div>

          {/* 4. Khung nội dung Preview & Editor */}
          <div className="flex-1 overflow-y-auto bg-slate-100/70 p-6">
            <div className="mx-auto max-w-2xl rounded-xl border border-slate-300 bg-white p-8 shadow-sm">
              {isEditing ? (
                <textarea
                  value={currentText}
                  onChange={e => setCustomText(e.target.value)}
                  rows={28}
                  className="w-full resize-y rounded-lg border border-slate-300 p-4 text-[14pt] leading-relaxed text-slate-900 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                  style={{ fontFamily: "'Times New Roman', Times, Georgia, serif" }}
                />
              ) : (
                <div
                  className="select-text text-[13.5pt] leading-[1.38] text-black"
                  style={{ fontFamily: "'Times New Roman', Times, Georgia, serif" }}
                >
                  <p className="font-bold text-black mb-1">
                    <strong>{shiftName}- PXVH1 xin gửi các anh (chị) báo cáo gồm:</strong>
                  </p>
                  <p className="font-bold text-black mb-1">
                    <strong>1. Chỉ tiêu kinh tế kỹ thuật:</strong>
                  </p>

                  {/* S1 */}
                  <p className="font-bold text-black mb-0.5">
                    <strong>- Tổ máy S1 vận hành:</strong>
                  </p>
                  <p className="text-black mb-0.5">+ Tổng sản lượng đầu cực máy phát S1: {metrics.grossMwhS1 != null ? metrics.grossMwhS1.toFixed(2) : "—"} (MWh)</p>
                  <p className="text-black mb-0.5">+ Tổng sản lượng tại điểm mua bán điện S1: {metrics.netMwhS1 != null ? metrics.netMwhS1.toFixed(2) : "—"} (MWh)</p>
                  <p className="text-black mb-0.5">+ Lượng điện tự dùng S1: {metrics.auxMwhS1 != null ? metrics.auxMwhS1.toFixed(2) : "—"} (MWh)</p>
                  <p className="text-black mb-0.5">+ Phần trăm điện tự dùng S1: {metrics.auxPercentS1 != null ? metrics.auxPercentS1.toFixed(2) : "—"} % (đã bao gồm tổn thất MBA)</p>
                  <p className="text-black mb-0.5">+ Tổng lượng than tiêu thụ S1: {metrics.coalTonnesS1 != null ? metrics.coalTonnesS1.toFixed(3) : "—"} (tấn) - đã quy ẩm về 8.5%</p>
                  <p className="text-black mb-0.5">+ Suất tiêu hao than tinh S1: {metrics.netCoalRateS1 != null ? metrics.netCoalRateS1.toFixed(3) : "—"} (g/kWh)</p>
                  <p className="text-black mb-0.5">+ Nhiệt trị than quy ẩm: {metrics.hhvKjKgS1 != null ? metrics.hhvKjKgS1.toFixed(2) : "—"} (kJ/kg)</p>
                  <p className="text-black mb-0.5">+ Suất hao nhiệt tinh S1: {metrics.netHeatRateS1 != null ? metrics.netHeatRateS1.toFixed(3) : "—"} (kJ/kWh)</p>
                  <p className="text-black mb-0.5">+ Tổng lượng hơi tiêu thụ S1: {metrics.steamTonnesS1 != null ? metrics.steamTonnesS1.toFixed(2) : "—"} (tấn)</p>
                  <p className="text-black mb-0.5">+ Suất tiêu hao hơi theo sản lượng đầu cực S1: {metrics.steamRateGrossS1 != null ? metrics.steamRateGrossS1.toFixed(2) : "—"} (g/kWh)</p>
                  <p className="text-black mb-0.5">+ Suất tiêu hao hơi theo sản lượng phát lưới S1: {metrics.steamRateNetS1 != null ? metrics.steamRateNetS1.toFixed(2) : "—"} (g/kWh)</p>
                  <p className="text-black mb-1">+ Lượng nước demin sử dụng S1: {metrics.deminWaterS1 != null ? metrics.deminWaterS1.toFixed(2) : "—"} (tấn)</p>

                  {/* S2 */}
                  <p className="font-bold text-black mb-0.5">
                    <strong>- Tổ máy S2 vận hành:</strong>
                  </p>
                  <p className="text-black mb-0.5">+ Tổng sản lượng đầu cực máy phát S2: {metrics.grossMwhS2 != null ? metrics.grossMwhS2.toFixed(2) : "—"} (MWh)</p>
                  <p className="text-black mb-0.5">+ Tổng sản lượng tại điểm mua bán điện S2: {metrics.netMwhS2 != null ? metrics.netMwhS2.toFixed(2) : "—"} (MWh)</p>
                  <p className="text-black mb-0.5">+ Lượng điện tự dùng S2: {metrics.auxMwhS2 != null ? metrics.auxMwhS2.toFixed(2) : "—"} (MWh)</p>
                  <p className="text-black mb-0.5">+ Phần trăm điện tự dùng S2: {metrics.auxPercentS2 != null ? metrics.auxPercentS2.toFixed(2) : "—"} % (đã bao gồm tổn thất MBA)</p>
                  <p className="text-black mb-0.5">+ Tổng lượng than tiêu thụ S2: {metrics.coalTonnesS2 != null ? metrics.coalTonnesS2.toFixed(3) : "—"} (tấn) - đã quy ẩm về 8.5%</p>
                  <p className="text-black mb-0.5">+ Suất tiêu hao than tinh S2: {metrics.netCoalRateS2 != null ? metrics.netCoalRateS2.toFixed(3) : "—"} (g/kWh)</p>
                  <p className="text-black mb-0.5">+ Nhiệt trị than quy ẩm: {metrics.hhvKjKgS2 != null ? metrics.hhvKjKgS2.toFixed(2) : "—"} (kJ/kg)</p>
                  <p className="text-black mb-0.5">+ Suất hao nhiệt tinh S2: {metrics.netHeatRateS2 != null ? metrics.netHeatRateS2.toFixed(3) : "—"} (kJ/kWh)</p>
                  <p className="text-black mb-0.5">+ Tổng lượng hơi tiêu thụ S2: {metrics.steamTonnesS2 != null ? metrics.steamTonnesS2.toFixed(2) : "—"} (tấn)</p>
                  <p className="text-black mb-0.5">+ Suất tiêu hao hơi theo sản lượng đầu cực S2: {metrics.steamRateGrossS2 != null ? metrics.steamRateGrossS2.toFixed(2) : "—"} (g/kWh)</p>
                  <p className="text-black mb-0.5">+ Suất tiêu hao hơi theo sản lượng phát lưới S2: {metrics.steamRateNetS2 != null ? metrics.steamRateNetS2.toFixed(2) : "—"} (g/kWh)</p>
                  <p className="text-black mb-1">+ Lượng nước demin sử dụng S2: {metrics.deminWaterS2 != null ? metrics.deminWaterS2.toFixed(2) : "—"} (tấn)</p>

                  <div className="h-3"></div>

                  {/* Toàn nhà máy */}
                  <p className="text-black mb-0.5">- Tổng lượng than nhập kho 24h theo số liệu từ PX nhiêu liệu: {metrics.coalIntake24h != null ? metrics.coalIntake24h.toFixed(2).replace(/\.00$/, "") : "0"} (tấn)</p>
                  <p className="text-black mb-0.5">- Tổng lượng NH3 tiêu thụ trong ngày: {metrics.nh3UsedTonnes != null ? metrics.nh3UsedTonnes.toFixed(2) : "—"} (tấn)</p>
                  <p className="text-black mb-0.5">- Suất tiêu hao NH3 theo sản lượng đầu cực: {metrics.nh3RateGross != null ? metrics.nh3RateGross.toFixed(2) : "—"} (g/kWh)</p>
                  <p className="text-black mb-0.5">- Suất tiêu hao NH3 theo sản lượng phát lưới: {metrics.nh3RateNet != null ? metrics.nh3RateNet.toFixed(2) : "—"} (g/kWh)</p>
                  <p className="text-black mb-0.5">- Tổng lượng NH3 tồn kho: {metrics.nh3Stock24h != null ? metrics.nh3Stock24h.toFixed(3) : "—"} (tấn)</p>
                  <p className="text-black mb-2">- NH3 nhập trong ngày: {metrics.nh3IntakeDay != null ? metrics.nh3IntakeDay.toFixed(2) : "—"} (tấn)</p>

                  {/* Danh sách file */}
                  <p className="font-bold text-black mb-1">
                    <strong>2. Báo cáo bao gồm các file:</strong>
                  </p>
                  <p className="text-black mb-0.5">- CTKTKT;</p>
                  <p className="text-black mb-0.5">- BCSX NMĐ S1;</p>
                  <p className="text-black mb-0.5">- BCSX NMĐ S2;</p>
                  <p className="text-black mb-0.5">- BCSX NMĐ A0;</p>
                  <p className="text-black mb-2">- Bảng theo dõi nước bổ sung trong ca;</p>

                  <div className="h-3"></div>
                  <p className="text-black">Trân trọng!</p>
                </div>
              )}
            </div>
          </div>

          {/* 5. Footer Dialog */}
          <div className="flex items-center justify-between border-t border-slate-200 bg-slate-50/80 px-6 py-3.5">
            <span className="text-xs text-slate-500">
              Mẹo: Nhấn nút <strong>Sao chép gửi mail</strong>, sau đó mở phần mềm Mail (Outlook/Thunderbird/Gmail) và dán (Ctrl+V) vào thân thư.
            </span>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={onClose}
                className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100"
              >
                Đóng
              </button>
              <button
                type="button"
                onClick={handleCopy}
                className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white shadow-xs hover:bg-blue-700"
              >
                <Copy className="size-3.5" />
                {copied ? "Đã chép!" : "Sao chép nội dung"}
              </button>
            </div>
          </div>
        </DialogPrimitive.Content>
      </DialogPrimitive.Portal>
    </DialogPrimitive.Root>
  );
}
