import { randomBytes, scryptSync } from "node:crypto";

function hashPassword(password: string): string {
  const salt = randomBytes(16).toString("hex");
  const hash = scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${hash}`;
}

export type Role = "admin" | "supervisor" | "technician" | "editor" | "viewer";
export type Permission =
  | "manage_users"
  | "edit_monthly_kpi"
  | "edit_daily_inputs"
  | "edit_ppa"
  | "edit_pmis"
  | "edit_bcsx"
  | "edit_water"
  | "sync_qlkt"
  | "sync_google_sheet"
  | "view_all";

export const PERMISSIONS: Permission[] = [
  "manage_users",
  "edit_monthly_kpi",
  "edit_daily_inputs",
  "edit_ppa",
  "edit_pmis",
  "edit_bcsx",
  "edit_water",
  "sync_qlkt",
  "sync_google_sheet",
  "view_all",
];

export type PositionSeed = {
  position: string;
  category: string;
  role: Role;
  permissions: Permission[];
  description: string;
};

export type UserSeed = {
  employeeCode: string;
  displayName: string;
  emailCompany: string;
  emailWork: string;
  phone: string;
  position: string;
  department: string;
  role: Role;
  username: string;
  rawPassword: string;
  status: "active" | "locked";
};

export const DEFAULT_POSITIONS: PositionSeed[] = [
  // Khối Lãnh đạo & Kỹ thuật
  {
    position: "Quản đốc",
    category: "Lãnh đạo",
    role: "admin",
    permissions: [...PERMISSIONS],
    description: "Toàn quyền quản trị hệ thống, phân quyền và phê duyệt",
  },
  {
    position: "Phó Quản đốc",
    category: "Lãnh đạo",
    role: "admin",
    permissions: [...PERMISSIONS],
    description: "Toàn quyền quản trị hệ thống, xem và điều hành số liệu",
  },
  {
    position: "Kỹ thuật viên",
    category: "Kỹ thuật",
    role: "technician",
    permissions: [
      "view_all",
      "edit_monthly_kpi",
      "edit_daily_inputs",
      "edit_ppa",
      "edit_pmis",
      "edit_water",
      "sync_qlkt",
      "sync_google_sheet",
    ],
    description: "Quản lý chỉ tiêu KTKT, nhập số liệu ngày, SHN PPA và báo cáo PMIS",
  },
  {
    position: "Thống kê",
    category: "Kỹ thuật",
    role: "editor",
    permissions: [
      "view_all",
      "edit_monthly_kpi",
      "edit_daily_inputs",
      "edit_water",
      "sync_qlkt",
    ],
    description: "Thống kê chỉ tiêu và số liệu sản xuất",
  },

  // Khối Giám sát & Điều hành ca
  {
    position: "Trưởng ca",
    category: "Vận hành ca",
    role: "supervisor",
    permissions: [
      "view_all",
      "edit_bcsx",
      "edit_daily_inputs",
      "edit_water",
      "sync_qlkt",
    ],
    description: "Giám sát vận hành ca, nhập 48 điểm nửa giờ và xuất báo cáo BCSX",
  },
  {
    position: "TK Lò máy",
    category: "Vận hành ca",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trưởng kíp Lò - Máy",
  },
  {
    position: "Trưởng kíp điện",
    category: "Vận hành ca",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trưởng kíp Điện",
  },

  // Khối Lò - Máy
  {
    position: "Lò trưởng",
    category: "Khối Lò",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trưởng kíp Lò hơi",
  },
  {
    position: "Lò phó",
    category: "Khối Lò",
    role: "viewer",
    permissions: ["view_all"],
    description: "Phó kíp Lò hơi",
  },
  {
    position: "Máy trưởng",
    category: "Khối Máy",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trưởng kíp Tua bin - Máy phát",
  },
  {
    position: "Máy phó",
    category: "Khối Máy",
    role: "viewer",
    permissions: ["view_all"],
    description: "Phó kíp Tua bin",
  },
  {
    position: "Máy nghiền",
    category: "Khối Lò",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành hệ thống máy nghiền than",
  },

  // Khối Điện & Đo lường
  {
    position: "Trực chính Điện",
    category: "Khối Điện",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trực chính hệ thống điện nhà máy",
  },
  {
    position: "Trực phụ điện",
    category: "Khối Điện",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trực phụ hệ thống điện nhà máy",
  },
  {
    position: "Thiết bị đo lường điều khiển",
    category: "Đo lường",
    role: "viewer",
    permissions: ["view_all"],
    description: "Theo dõi hệ thống đo lường & điều khiển",
  },

  // Khối Môi trường & Hóa học
  {
    position: "FGD",
    category: "Môi trường",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành hệ thống khử lưu huỳnh FGD",
  },
  {
    position: "ESP",
    category: "Môi trường",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành hệ thống lọc bụi tĩnh điện ESP",
  },
  {
    position: "NH3 - Lò hơi phụ",
    category: "Môi trường",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành hệ thống NH3 khử NOx & Lò hơi phụ",
  },
  {
    position: "XLN hỗn hợp",
    category: "Hóa nước",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành trạm xử lý nước hỗn hợp",
  },
  {
    position: "XLNT",
    category: "Hóa nước",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành trạm xử lý nước thải",
  },

  // Khối Phụ trợ & Nhiên liệu
  {
    position: "Khí Nén – Nhà Dầu",
    category: "Phụ trợ",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành trạm khí nén và nhà dầu",
  },
  {
    position: "Thải xỉ",
    category: "Phụ trợ",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành hệ thống thải xỉ xỉ đáy lò",
  },
  {
    position: "Trạm bơm nước thô",
    category: "Phụ trợ",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành trạm bơm nước thô cấp nước nhà máy",
  },
  {
    position: "Trạm bơm tuần hoàn",
    category: "Phụ trợ",
    role: "viewer",
    permissions: ["view_all"],
    description: "Vận hành trạm bơm nước làm mát tuần hoàn",
  },
  {
    position: "Trợ thủ",
    category: "Phụ trợ",
    role: "viewer",
    permissions: ["view_all"],
    description: "Trợ thủ vận hành thiết bị phụ trợ",
  },
];

export const INITIAL_USERS: UserSeed[] = [
  {
    employeeCode: "NĐDH0132",
    displayName: "Nguyễn Phương Hiếu",
    emailCompany: "hieunp@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "hieunp",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0175",
    displayName: "Lê Thành Triệu",
    emailCompany: "trieult@tpcduyenhai.com.vn",
    emailWork: "Trieu.lt1.tpcduyenhai@gmail.com",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "trieult",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0211",
    displayName: "Lê Phạm Minh Thông",
    emailCompany: "thonglpm@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "thonglpm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0704",
    displayName: "Nguyễn Thanh Lâm",
    emailCompany: "lamnt1@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "lamnt1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1156",
    displayName: "Nguyễn Thanh Liêm",
    emailCompany: "liemnt@tpcduyenhai.com.vn",
    emailWork: "liem.nt.cbsxdh1@gmail.com",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "liemnt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1220",
    displayName: "Nguyễn Tấn An",
    emailCompany: "annt5@tpcduyenhai.com.vn",
    emailWork: "an.nt5.cbsxdh1@gmail.com",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "annt5",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1221",
    displayName: "Trần Thanh Long",
    emailCompany: "longtt1@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "longtt1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1450",
    displayName: "Nguyễn Hoàng Thái",
    emailCompany: "thainh@tpcduyenhai.com.vn",
    emailWork: "thai.nh.cbsxdh1@gmail.com",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "thainh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1538",
    displayName: "Võ Hoàng Ân",
    emailCompany: "anvh@tpcduyenhai.com.vn",
    emailWork: "An.vh.tpcduyenhai@gmail.com",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "anvh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1552",
    displayName: "Nguyễn Trung Khánh",
    emailCompany: "khanhnt@tpcduyenhai.com.vn",
    emailWork: "khanh.nt.tpcduyenhai@gmail.com",
    phone: "",
    position: "ESP",
    department: "Vận hành 1",
    role: "viewer",
    username: "khanhnt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0180",
    displayName: "Nguyễn Văn Thiện",
    emailCompany: "thiennv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "thiennv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0201",
    displayName: "Nguyễn Nhựt Duy",
    emailCompany: "duynn@tpcduyenhai.com.vn",
    emailWork: "nguyenduy15091992@gmail.com",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "duynn",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0688",
    displayName: "Lê Tấn Trung",
    emailCompany: "trunglt@tpcduyenhai.com.vn",
    emailWork: "trung.lt.nddh3@gmail.com",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "trunglt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0698",
    displayName: "Thạch Ly Qui",
    emailCompany: "quitl@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "quitl",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1184",
    displayName: "Lâm Công Minh",
    emailCompany: "minhlc@tpcduyenhai.com.vn",
    emailWork: "minh.lc.cbsxdh1@gmail.com",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "admin",
    username: "minhlc",
    rawPassword: "Cogidau3@",
    status: "active",
  },
  {
    employeeCode: "NĐDH1225",
    displayName: "Dương Minh Phú",
    emailCompany: "phudm@tpcduyenhai.com.vn",
    emailWork: "dmphu.pxvh1@gmail.com",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "phudm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1304",
    displayName: "Thạch Út",
    emailCompany: "utt1@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "utt1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1534",
    displayName: "Nguyễn Quốc Đạt",
    emailCompany: "datnq@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "datnq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1599",
    displayName: "Trần Triệu Vĩ",
    emailCompany: "vitt@tpcduyenhai.com.vn",
    emailWork: "trieuvi11122000@gmail.com",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "vitt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NDDH1602",
    displayName: "Trần Văn Đồi",
    emailCompany: "doitv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "doitv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NDDH1612",
    displayName: "Nguyễn Thanh Lâm",
    emailCompany: "lamnt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "FGD",
    department: "Vận hành 1",
    role: "viewer",
    username: "lamnt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0170",
    displayName: "Nguyễn Đông Phi",
    emailCompany: "phind@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Khí Nén – Nhà Dầu",
    department: "Vận hành 1",
    role: "viewer",
    username: "phind",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0182",
    displayName: "Nguyễn Văn Ấu",
    emailCompany: "aunv@tpcduyenhai.com.vn",
    emailWork: "nguyenvanaulh2022@gmail.com",
    phone: "",
    position: "Khí Nén – Nhà Dầu",
    department: "Vận hành 1",
    role: "viewer",
    username: "aunv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1136",
    displayName: "Huỳnh Minh Đầy",
    emailCompany: "dayhm@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Khí Nén – Nhà Dầu",
    department: "Vận hành 1",
    role: "viewer",
    username: "dayhm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1543",
    displayName: "Lê Hoàng Qui",
    emailCompany: "quilh@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Khí Nén – Nhà Dầu",
    department: "Vận hành 1",
    role: "viewer",
    username: "quilh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1544",
    displayName: "Cao Minh Nhựt",
    emailCompany: "nhutcm@tpcduyenhai.com.vn",
    emailWork: "nhutcao1993@gmail.com",
    phone: "",
    position: "Khí Nén – Nhà Dầu",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhutcm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0049",
    displayName: "Phan Minh Hải",
    emailCompany: "haipm@tpcduyenhai.com.vn",
    emailWork: "phanhai61174@gmail.com",
    phone: "",
    position: "Kỹ thuật viên",
    department: "Vận hành 1",
    role: "technician",
    username: "haipm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0052",
    displayName: "Nguyễn Khắc Bảo",
    emailCompany: "baonk@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Kỹ thuật viên",
    department: "Vận hành 1",
    role: "technician",
    username: "baonk",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0082",
    displayName: "Bùi Hoài Tâm",
    emailCompany: "tambh@tpcduyenhai.com.vn",
    emailWork: "tam.bh.cbsxdh1@gmail.com",
    phone: "",
    position: "Kỹ thuật viên",
    department: "Vận hành 1",
    role: "technician",
    username: "tambh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0120",
    displayName: "Vũ Văn Tiến",
    emailCompany: "tienvv@tpcduyenhai.com.vn",
    emailWork: "tien.vv.cbsxdh1@gmail.com",
    phone: "",
    position: "Kỹ thuật viên",
    department: "Vận hành 1",
    role: "technician",
    username: "tienvv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0224",
    displayName: "Nguyễn Quang Đàm",
    emailCompany: "damnq@tpcduyenhai.com.vn",
    emailWork: "dam.nq.cbsxdh1@gmail.com",
    phone: "",
    position: "Kỹ thuật viên",
    department: "Vận hành 1",
    role: "technician",
    username: "damnq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0111",
    displayName: "Phan Thanh Truyền",
    emailCompany: "truyenpt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "truyenpt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0177",
    displayName: "Phạm Hoài Nam",
    emailCompany: "namph@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "namph",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0245",
    displayName: "Lê Văn Sơn",
    emailCompany: "sonlv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "sonlv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0246",
    displayName: "Nguyễn Văn Tèo",
    emailCompany: "teonv@tpcduyenhai.com.vn",
    emailWork: "teo.nv.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "teonv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0247",
    displayName: "Trần Văn Thạch",
    emailCompany: "thactv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "thactv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0461",
    displayName: "Trần Văn Phúc",
    emailCompany: "phuctv@tpcduyenhai.com.vn",
    emailWork: "phuc.tv.nddh3@gmail.com",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "phuctv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0975",
    displayName: "Từ Chí Thiện",
    emailCompany: "thientc@tpcduyenhai.com.vn",
    emailWork: "thien.tc.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "thientc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1181",
    displayName: "Phạm Thanh Điền",
    emailCompany: "dienpt@tpcduyenhai.com.vn",
    emailWork: "dien.pt2.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "dienpt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1299",
    displayName: "Bùi Chí Tâm",
    emailCompany: "tambc@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "tambc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1323",
    displayName: "Nguyễn Quang Trạng",
    emailCompany: "trangnq@tpcduyenhai.com.vn",
    emailWork: "trang.nq.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "trangnq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1453",
    displayName: "Mai Đoàn Kim Khánh",
    emailCompany: "khanhmdk@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "admin",
    username: "khanhmdk",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1530",
    displayName: "Kiên Văn Chí Thanh",
    emailCompany: "thanhkvc@tpcduyenhai.com.vn",
    emailWork: "thanhkvc.tpcduyenhai@gmail.com",
    phone: "",
    position: "Lò phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "thanhkvc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0086",
    displayName: "Đỗ Văn Luân",
    emailCompany: "luandv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "luandv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0136",
    displayName: "Nguyễn Thành Nam",
    emailCompany: "namnt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "namnt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0159",
    displayName: "Phạm Xuân Long",
    emailCompany: "longpx@tpcduyenhai.com.vn",
    emailWork: "long.px.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "longpx",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0168",
    displayName: "Lê Văn Chung",
    emailCompany: "chunglv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "chunglv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0206",
    displayName: "Thạch Nhâm",
    emailCompany: "nhamt@tpcduyenhai.com.vn",
    emailWork: "nham.t.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhamt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0623",
    displayName: "Tiết Thanh Hải",
    emailCompany: "haitt@tpcduyenhai.com.vn",
    emailWork: "thanhhaitiet@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "haitt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0659",
    displayName: "Lê Văn Đạo",
    emailCompany: "daolv@tpcduyenhai.com.vn",
    emailWork: "dao.lv.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "daolv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0671",
    displayName: "Phạm Biên Thùy",
    emailCompany: "thuypb@tpcduyenhai.com.vn",
    emailWork: "thuy.pb.nddh3@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "thuypb",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0691",
    displayName: "Nguyễn Văn Sang",
    emailCompany: "Sangnv@tpcduyenhai.com.vn",
    emailWork: "sang.nv.nddh3@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "Sangnv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1196",
    displayName: "Nguyễn Hải Quân",
    emailCompany: "quannh1@tpcduyenhai.com.vn",
    emailWork: "quan.nh1.cbsxdh1@gmail.com",
    phone: "",
    position: "Lò trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "quannh1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0113",
    displayName: "Trương Hoàng Vũ",
    emailCompany: "vuth@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "vuth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0134",
    displayName: "Trần Văn Hưởng",
    emailCompany: "huongtv@tpcduyenhai.com.vn",
    emailWork: "huong.tv.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "huongtv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0572",
    displayName: "Trần Trọng Tín",
    emailCompany: "tintt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "tintt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0694",
    displayName: "Lý Thanh Khoa",
    emailCompany: "khoalt@tpcduyenhai.com.vn",
    emailWork: "khoa.lt.nddh3@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "khoalt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0703",
    displayName: "Nguyễn Thành Đô",
    emailCompany: "dont@tpcduyenhai.com.vn",
    emailWork: "do.nt.nddh3@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "dont",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1182",
    displayName: "Vương Chí Hiếu",
    emailCompany: "hieuvc@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "hieuvc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1383",
    displayName: "Cao Bá Huy",
    emailCompany: "huycb@tpcduyenhai.com.vn",
    emailWork: "huy.cb.nddh1@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "huycb",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1384",
    displayName: "Trần Lưu Bá Phúc",
    emailCompany: "phuctlb@tpcduyenhai.com.vn",
    emailWork: "tlbp222222@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "phuctlb",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1439",
    displayName: "Mai Văn Minh Kha",
    emailCompany: "khamvm@tpcduyenhai.com.vn",
    emailWork: "kha.mvm.tpcduyenhai@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "khamvm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1474",
    displayName: "Lê Hoài Thắng",
    emailCompany: "thanglh@tpcduyenhai.com.vn",
    emailWork: "lhthang1510@gmail.com",
    phone: "",
    position: "Máy nghiền",
    department: "Vận hành 1",
    role: "viewer",
    username: "thanglh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0094",
    displayName: "Tài Duy Phúc",
    emailCompany: "phuctd@tpcduyenhai.com.vn",
    emailWork: "duyphuctpcduyenhai@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "phuctd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0135",
    displayName: "Đỗ Minh Luân",
    emailCompany: "luandm@tpcduyenhai.com.vn",
    emailWork: "luan.dm.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "luandm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0146",
    displayName: "Trần Hoàng Tú",
    emailCompany: "tuth@tpcduyenhai.com.vn",
    emailWork: "tu.th.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "tuth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0158",
    displayName: "Trần Tấn Đạt",
    emailCompany: "dattt@tpcduyenhai.com.vn",
    emailWork: "dat.tt.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "dattt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0214",
    displayName: "Nguyễn Minh Trung",
    emailCompany: "trungnm@tpcduyenhai.com.vn",
    emailWork: "trung.nm.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "trungnm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1322",
    displayName: "Cao Văn Tèo",
    emailCompany: "teocv@tpcduyenhai.com.vn",
    emailWork: "teo.cv.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "teocv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1324",
    displayName: "Đỗ Hiếu Liêm",
    emailCompany: "Liemdh@tpcduyenhai.com.vn",
    emailWork: "liem.dh.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "Liemdh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1408",
    displayName: "Hà Hữu Hiệp",
    emailCompany: "hiephh@tpcduyenhai.com.vn",
    emailWork: "hiep.hh.tpcduyenhai@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "hiephh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1438",
    displayName: "Hoàng Vĩnh Phúc",
    emailCompany: "phuchv@tpcduyenhai.com.vn",
    emailWork: "hoangphuccdsp190@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "phuchv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1461",
    displayName: "Phạm Quốc Đạt",
    emailCompany: "datpq1@tpcduyenhai.com.vn",
    emailWork: "datpq1.tpcduyenhai@gmail.com",
    phone: "",
    position: "Máy phó",
    department: "Vận hành 1",
    role: "viewer",
    username: "datpq1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0083",
    displayName: "Cao Tấn Phát",
    emailCompany: "phatct@tpcduyenhai.com.vn",
    emailWork: "phat.ct.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "phatct",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0109",
    displayName: "Tống Minh Thức",
    emailCompany: "thuctm@tpcduyenhai.com.vn",
    emailWork: "thuc.tm.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "thuctm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0129",
    displayName: "Hà Thanh Xuyên",
    emailCompany: "xuyenht@tpcduyenhai.com.vn",
    emailWork: "xuyen.ht.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "xuyenht",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0172",
    displayName: "Phan Phú Quí",
    emailCompany: "quipp@tpcduyenhai.com.vn",
    emailWork: "quipp@tpcduyenhai.com.vn",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "quipp",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0176",
    displayName: "Bùi Quốc Tuấn",
    emailCompany: "tuanbq@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "tuanbq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0231",
    displayName: "Lư Văn Lay Mol",
    emailCompany: "mollvl@tpcduyenhai.com.vn",
    emailWork: "mol.lvl.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "mollvl",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0434",
    displayName: "Võ Chí Thịnh",
    emailCompany: "thinhvc@tpcduyenhai.com.vn",
    emailWork: "thinh.vc1.nddh3@gmail.com",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "thinhvc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0437",
    displayName: "Nguyễn Văn Trí",
    emailCompany: "trinv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "trinv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0458",
    displayName: "Nguyễn Văn Qươn",
    emailCompany: "quonnv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "quonnv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1327",
    displayName: "Trần Văn Cương",
    emailCompany: "cuongtv@tpcduyenhai.com.vn",
    emailWork: "cuong.tv.cbsxdh1@gmail.com",
    phone: "",
    position: "Máy trưởng",
    department: "Vận hành 1",
    role: "viewer",
    username: "cuongtv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0078",
    displayName: "Trương Quốc Hiếu",
    emailCompany: "hieutq@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "NH3 - Lò hơi phụ",
    department: "Vận hành 1",
    role: "viewer",
    username: "hieutq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0079",
    displayName: "Trần Hoàng Tuấn",
    emailCompany: "tuanth@tpcduyenhai.com.vn",
    emailWork: "tuan.th.cbsxdh1@gmail.com",
    phone: "",
    position: "NH3 - Lò hơi phụ",
    department: "Vận hành 1",
    role: "viewer",
    username: "tuanth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0096",
    displayName: "Đoàn Minh Hải",
    emailCompany: "haidm@tpcduyenhai.com.vn",
    emailWork: "hai.dm.cbsxdh1@gmail.com",
    phone: "",
    position: "NH3 - Lò hơi phụ",
    department: "Vận hành 1",
    role: "viewer",
    username: "haidm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1019",
    displayName: "Tăng Vũ Lộc",
    emailCompany: "loctv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "NH3 - Lò hơi phụ",
    department: "Vận hành 1",
    role: "viewer",
    username: "loctv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1135",
    displayName: "Đinh Ngọc Nhường",
    emailCompany: "nhuongdn@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "NH3 - Lò hơi phụ",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhuongdn",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0151",
    displayName: "Nguyễn Văn Cường",
    emailCompany: "cuongnv@tpcduyenhai.com.vn",
    emailWork: "cuong.nv.cbsxdh1@gmail.com",
    phone: "",
    position: "Phó Quản đốc",
    department: "Vận hành 1",
    role: "admin",
    username: "cuongnv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0223",
    displayName: "Nguyễn Ngọc Yên",
    emailCompany: "yennn@tpcduyenhai.com.vn",
    emailWork: "yen.nn.cbsxdh1@gmail.com",
    phone: "",
    position: "Phó Quản đốc",
    department: "Vận hành 1",
    role: "admin",
    username: "yennn",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0048",
    displayName: "Trương Trần Hoàng Huân",
    emailCompany: "huantth@tpcduyenhai.com.vn",
    emailWork: "huan.tth.cbsxdh1@gmail.com",
    phone: "",
    position: "Quản đốc",
    department: "Vận hành 1",
    role: "admin",
    username: "huantth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0104",
    displayName: "Đường Thái Sơn",
    emailCompany: "sondt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Thải xỉ",
    department: "Vận hành 1",
    role: "viewer",
    username: "sondt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0137",
    displayName: "Nguyễn Xuân Nhâm",
    emailCompany: "nhamnx@tpcduyenhai.com.vn",
    emailWork: "nham.nx.cbsxdh1@gmail.com",
    phone: "",
    position: "Thải xỉ",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhamnx",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0248",
    displayName: "Nguyễn Văn Thạch",
    emailCompany: "thachnv@tpcduyenhai.com.vn",
    emailWork: "tranthach.nv.cbsxdh1@gmail.com",
    phone: "",
    position: "Thải xỉ",
    department: "Vận hành 1",
    role: "viewer",
    username: "thachnv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0305",
    displayName: "Nguyễn Đình Nam",
    emailCompany: "namnd@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Thải xỉ",
    department: "Vận hành 1",
    role: "viewer",
    username: "namnd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1302",
    displayName: "Kim Duy Tính",
    emailCompany: "tinhkd@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Thải xỉ",
    department: "Vận hành 1",
    role: "viewer",
    username: "tinhkd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0055",
    displayName: "Hứa Văn Tài",
    emailCompany: "taihv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "taihv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0056",
    displayName: "Châu Văn Khoa",
    emailCompany: "khoacv@tpcduyenhai.com.vn",
    emailWork: "khoa.cv.cbsxdh1@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "khoacv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0060",
    displayName: "Đặng Hoàng Long",
    emailCompany: "longdh@tpcduyenhai.com.vn",
    emailWork: "long.dh.cbsxdh1@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "longdh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0062",
    displayName: "Trần Duy Khang",
    emailCompany: "khangtd@tpcduyenhai.com.vn",
    emailWork: "duykhangcn@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "khangtd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0063",
    displayName: "Nguyễn Chí Linh",
    emailCompany: "linhnc@tpcduyenhai.com.vn",
    emailWork: "linh.nc.cbsxdh1@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "linhnc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0181",
    displayName: "Phan Văn Sang",
    emailCompany: "sangpv@tpcduyenhai.com.vn",
    emailWork: "sang.pv.cbsxdh1@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "sangpv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0494",
    displayName: "Lâm Quang Hiền",
    emailCompany: "hienlq@tpcduyenhai.com.vn",
    emailWork: "hien.lq.nddh3@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "hienlq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0497",
    displayName: "Nguyễn Thanh Bá",
    emailCompany: "bant@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "bant",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1115",
    displayName: "Nguyễn Văn Hiếu",
    emailCompany: "hieunv2@tpcduyenhai.com.vn",
    emailWork: "hieu.nv2.cbsxdh1@gmail.com",
    phone: "",
    position: "Thiết bị đo lường điều khiển",
    department: "Vận hành 1",
    role: "viewer",
    username: "hieunv2",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0813",
    displayName: "Hà Thị Mẫn",
    emailCompany: "manht@tpcduyenhai.com.vn",
    emailWork: "man.ht.cbsxdh1@gmail.com",
    phone: "",
    position: "Thống kê",
    department: "Vận hành 1",
    role: "viewer",
    username: "manht",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1209",
    displayName: "Triệu Tuyết Nhung",
    emailCompany: "nhungtt@tpcduyenhai.com.vn",
    emailWork: "nhung.ttcbsxdh1@gmail.com",
    phone: "",
    position: "Thống kê",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhungtt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0087",
    displayName: "Nguyễn Văn Chiến",
    emailCompany: "chiennv@tpcduyenhai.com.vn",
    emailWork: "chien.nv.cbsxdh1@gmail.com",
    phone: "",
    position: "TK Lò máy",
    department: "Vận hành 1",
    role: "viewer",
    username: "chiennv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0126",
    displayName: "Lê Hữu Nhân",
    emailCompany: "nhanlh@tpcduyenhai.com.vn",
    emailWork: "nhan.lh.cbsxdh1@gmail.com",
    phone: "",
    position: "TK Lò máy",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhanlh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0131",
    displayName: "Lương Huệ Châu",
    emailCompany: "chaulh@tpcduyenhai.com.vn",
    emailWork: "chau.lh.cbsxdh1@gmail.com",
    phone: "",
    position: "TK Lò máy",
    department: "Vận hành 1",
    role: "viewer",
    username: "chaulh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0152",
    displayName: "Trần Hoàng Đạt",
    emailCompany: "datth@tpcduyenhai.com.vn",
    emailWork: "dat.th.cbsxdh1@gmail.com",
    phone: "",
    position: "TK Lò máy",
    department: "Vận hành 1",
    role: "viewer",
    username: "datth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0222",
    displayName: "Đinh Trung Kiên",
    emailCompany: "kiendt@tpcduyenhai.com.vn",
    emailWork: "kien.dt.cbsxdh1@gmail.com",
    phone: "",
    position: "TK Lò máy",
    department: "Vận hành 1",
    role: "viewer",
    username: "kiendt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0141",
    displayName: "Hồ Minh Tình",
    emailCompany: "tinhhm@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trạm bơm nước thô",
    department: "Vận hành 1",
    role: "viewer",
    username: "tinhhm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0237",
    displayName: "Nguyễn Lê Trường An",
    emailCompany: "annlt@tpcduyenhai.com.vn",
    emailWork: "an.nlt.cbsxdh1@gmail.com",
    phone: "",
    position: "Trạm bơm nước thô",
    department: "Vận hành 1",
    role: "viewer",
    username: "annlt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0367",
    displayName: "Phạm Việt Linh",
    emailCompany: "linhpv1@tpcduyenhai.com.vn",
    emailWork: "linh.pv1.cbsxdh1@gmail.com",
    phone: "",
    position: "Trạm bơm nước thô",
    department: "Vận hành 1",
    role: "viewer",
    username: "linhpv1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0711",
    displayName: "Lâm Văn Lạc",
    emailCompany: "laclv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trạm bơm nước thô",
    department: "Vận hành 1",
    role: "viewer",
    username: "laclv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1179",
    displayName: "Nguyễn Chí Công",
    emailCompany: "congnc@tpcduyenhai.com.vn",
    emailWork: "cong.nc.cbsxdh1@gmail.com",
    phone: "",
    position: "Trạm bơm nước thô",
    department: "Vận hành 1",
    role: "viewer",
    username: "congnc",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0073",
    displayName: "Nguyễn Đức Huy",
    emailCompany: "huynd@tpcduyenhai.com.vn",
    emailWork: "huy.nd.cbsxdh1@gmail.com",
    phone: "",
    position: "Trạm bơm tuần hoàn",
    department: "Vận hành 1",
    role: "viewer",
    username: "huynd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0148",
    displayName: "Quảng Thành Yên",
    emailCompany: "yenqt@tpcduyenhai.com.vn",
    emailWork: "yen.qt.cbsxdh1@gmail.com",
    phone: "",
    position: "Trạm bơm tuần hoàn",
    department: "Vận hành 1",
    role: "viewer",
    username: "yenqt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0236",
    displayName: "Nguyễn Thái An",
    emailCompany: "annt1@tpcduyenhai.com.vn",
    emailWork: "an.nt.cbsxdh1@gmail.com",
    phone: "",
    position: "Trạm bơm tuần hoàn",
    department: "Vận hành 1",
    role: "viewer",
    username: "annt1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1436",
    displayName: "Lê Hoàng Phong",
    emailCompany: "phonglh@tpcduyenhai.com.vn",
    emailWork: "phong.lh.tpcduyenhai@gmail.com",
    phone: "",
    position: "Trạm bơm tuần hoàn",
    department: "Vận hành 1",
    role: "viewer",
    username: "phonglh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1540",
    displayName: "Lê Văn Cường",
    emailCompany: "cuonglv2@tpcduyenhai.com.vn",
    emailWork: "levancuongthinh1995@gmail.com",
    phone: "",
    position: "Trạm bơm tuần hoàn",
    department: "Vận hành 1",
    role: "viewer",
    username: "cuonglv2",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0124",
    displayName: "Nguyễn Quốc Chiến",
    emailCompany: "chiennq@tpcduyenhai.com.vn",
    emailWork: "chien.nq.cbsxdh1@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "chiennq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0165",
    displayName: "Trương Quang Vinh",
    emailCompany: "vinhtq@tpcduyenhai.com.vn",
    emailWork: "vinh.tq.cbsxdh1@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "vinhtq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0197",
    displayName: "Triệu Hồng Phát",
    emailCompany: "phatth@tpcduyenhai.com.vn",
    emailWork: "phat.th.cbsxdh1@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "phatth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0239",
    displayName: "Lê Quang Huy",
    emailCompany: "huylq@tpcduyenhai.com.vn",
    emailWork: "Huy.lq.cbsxdh1@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "huylq",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0473",
    displayName: "Hà Duy Khương",
    emailCompany: "khuonghd@tpcduyenhai.com.vn",
    emailWork: "khuong.hd.nddh3@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "khuonghd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1300",
    displayName: "Nguyễn Thành Tâm",
    emailCompany: "tamnt1@tpcduyenhai.com.vn",
    emailWork: "tam.nt1.cbsxdh1@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "tamnt1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1305",
    displayName: "Lê Tuấn An",
    emailCompany: "Anlt@tpcduyenhai.com.vn",
    emailWork: "an.lt.cbsxdh1@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "Anlt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1410",
    displayName: "Trương Hoàng Nguyên",
    emailCompany: "nguyenth@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "nguyenth",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1532",
    displayName: "Nguyễn Trà Giang",
    emailCompany: "giangnt2@tpcduyenhai.com.vn",
    emailWork: "giangnt2.tpcduyenhai@gmail.com",
    phone: "",
    position: "Trợ thủ",
    department: "Vận hành 1",
    role: "viewer",
    username: "giangnt2",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0075",
    displayName: "Huỳnh Đăng Vũ",
    emailCompany: "vuhd@tpcduyenhai.com.vn",
    emailWork: "vu.hd.cbsxdh1@gmail.com",
    phone: "",
    position: "Trực chính Điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "vuhd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0162",
    displayName: "Sơn Thái",
    emailCompany: "thais@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trực chính Điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "thais",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0580",
    displayName: "Đinh Ngọc Lâm",
    emailCompany: "lamdn@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trực chính Điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "lamdn",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1339",
    displayName: "Nguyễn Dương Dũng Hải",
    emailCompany: "haindd@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trực chính Điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "haindd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0102",
    displayName: "Lê Nhu",
    emailCompany: "nhul@tpcduyenhai.com.vn",
    emailWork: "lenhu0580@gmail.com",
    phone: "",
    position: "Trực phụ điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhul",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0145",
    displayName: "Phạm Thanh Tùng",
    emailCompany: "tungpt@tpcduyenhai.com.vn",
    emailWork: "tung.pt.cbsxdh1@gmail.com",
    phone: "",
    position: "Trực phụ điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "tungpt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0504",
    displayName: "Phan Thành Khoa",
    emailCompany: "khoapt@tpcduyenhai.com.vn",
    emailWork: "khoa.pt.nddh3@gmail.com",
    phone: "",
    position: "Trực phụ điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "khoapt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0562",
    displayName: "Đặng Tiến Phát",
    emailCompany: "phatdt@tpcduyenhai.com.vn",
    emailWork: "Phat.dt.cbsxdh1@gmail.com",
    phone: "",
    position: "Trực phụ điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "phatdt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1138",
    displayName: "Nguyễn Hữu Danh",
    emailCompany: "danhnh@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trực phụ điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "danhnh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1422",
    displayName: "Phan Thiện Nhân",
    emailCompany: "nhanpt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trực phụ điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhanpt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0130",
    displayName: "Nguyễn Ngọc Lễ",
    emailCompany: "lenn@tpcduyenhai.com.vn",
    emailWork: "le.nn.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng ca",
    department: "Vận hành 1",
    role: "supervisor",
    username: "lenn",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0153",
    displayName: "Nguyễn Lê Trung Việt",
    emailCompany: "vietnlt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trưởng ca",
    department: "Vận hành 1",
    role: "supervisor",
    username: "vietnlt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0156",
    displayName: "Lê Viết Châu",
    emailCompany: "chaulv@tpcduyenhai.com.vn",
    emailWork: "chau.lv.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng ca",
    department: "Vận hành 1",
    role: "supervisor",
    username: "chaulv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0221",
    displayName: "Nguyễn Minh Trọng",
    emailCompany: "trongnm@tpcduyenhai.com.vn",
    emailWork: "trong.nm.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng ca",
    department: "Vận hành 1",
    role: "supervisor",
    username: "trongnm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0226",
    displayName: "Đỗ Xuân Ni",
    emailCompany: "nidx@tpcduyenhai.com.vn",
    emailWork: "ni.dx.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng ca",
    department: "Vận hành 1",
    role: "supervisor",
    username: "nidx",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0090",
    displayName: "Võ Minh Chánh",
    emailCompany: "chanhvm@tpcduyenhai.com.vn",
    emailWork: "chanh.vm.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng kíp điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "chanhvm",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0106",
    displayName: "Nguyễn Văn Tân",
    emailCompany: "tannv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trưởng kíp điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "tannv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0163",
    displayName: "Trần Văn Thừa",
    emailCompany: "thuatv@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "Trưởng kíp điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "thuatv",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0185",
    displayName: "Trần Phước Nhân",
    emailCompany: "nhantp@tpcduyenhai.com.vn",
    emailWork: "nhan.tp.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng kíp điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhantp",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0249",
    displayName: "Huỳnh Duy Luân",
    emailCompany: "luanhd@tpcduyenhai.com.vn",
    emailWork: "luan.hd.cbsxdh1@gmail.com",
    phone: "",
    position: "Trưởng kíp điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "luanhd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0509",
    displayName: "Nguyễn Hữu Trung Nhân",
    emailCompany: "nhannht@tpcduyenhai.com.vn",
    emailWork: "nhan.nht1.nddh3@gmail.com",
    phone: "",
    position: "Trưởng kíp điện",
    department: "Vận hành 1",
    role: "viewer",
    username: "nhannht",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0098",
    displayName: "Phạm Thế Hiển",
    emailCompany: "hienpt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLN hỗn hợp",
    department: "Vận hành 1",
    role: "viewer",
    username: "hienpt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0179",
    displayName: "Nguyễn Duy Khánh",
    emailCompany: "khanhnd@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLN hỗn hợp",
    department: "Vận hành 1",
    role: "viewer",
    username: "khanhnd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0202",
    displayName: "Nguyễn Hoài Em",
    emailCompany: "emnh@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLN hỗn hợp",
    department: "Vận hành 1",
    role: "viewer",
    username: "emnh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0244",
    displayName: "Kim Như Quỳnh",
    emailCompany: "quynhkn@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLN hỗn hợp",
    department: "Vận hành 1",
    role: "viewer",
    username: "quynhkn",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1155",
    displayName: "Trần Thanh Phong",
    emailCompany: "phongtt1@tpcduyenhai.com.vn",
    emailWork: "phong.tt1.cbsxdh1@gmail.com",
    phone: "",
    position: "XLN hỗn hợp",
    department: "Vận hành 1",
    role: "viewer",
    username: "phongtt1",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1301",
    displayName: "Trần Đức Lợi",
    emailCompany: "loitd@tpcduyenhai.com.vn",
    emailWork: "loi.td.cbsxdh1@gmail.com",
    phone: "",
    position: "XLN hỗn hợp",
    department: "Vận hành 1",
    role: "viewer",
    username: "loitd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0167",
    displayName: "Ngô Hoàng Hôn",
    emailCompany: "honnh@tpcduyenhai.com.vn",
    emailWork: "hon.nh.cbsxdh1@gmail.com",
    phone: "",
    position: "XLNT",
    department: "Vận hành 1",
    role: "viewer",
    username: "honnh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0183",
    displayName: "Nguyễn Hoài Ân",
    emailCompany: "annh@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLNT",
    department: "Vận hành 1",
    role: "viewer",
    username: "annh",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH0216",
    displayName: "Hồ Duy Tuyến",
    emailCompany: "tuyenhd@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLNT",
    department: "Vận hành 1",
    role: "viewer",
    username: "tuyenhd",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1226",
    displayName: "Phạm Tuấn Kiệt",
    emailCompany: "kietpt@tpcduyenhai.com.vn",
    emailWork: "",
    phone: "",
    position: "XLNT",
    department: "Vận hành 1",
    role: "viewer",
    username: "kietpt",
    rawPassword: "password123",
    status: "active",
  },
  {
    employeeCode: "NĐDH1306",
    displayName: "Kiều Minh Chí",
    emailCompany: "chikm@tpcduyenhai.com.vn",
    emailWork: "chi.km.cbsxdh1@gmail.com",
    phone: "",
    position: "XLNT",
    department: "Vận hành 1",
    role: "viewer",
    username: "chikm",
    rawPassword: "password123",
    status: "active",
  },
];

export async function seedUsersAndPositions(rawDb: ReturnType<typeof import("@/db").getRawDb>) {
  // 1. Đảm bảo cấu trúc bảng tồn tại
  try {
    await rawDb.prepare(`
      CREATE TABLE IF NOT EXISTS position_permissions (
        id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
        position text NOT NULL,
        role text DEFAULT 'viewer' NOT NULL,
        permissions text DEFAULT '[]' NOT NULL,
        description text DEFAULT '' NOT NULL,
        updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
      )
    `).run();
    await rawDb.prepare(`CREATE UNIQUE INDEX IF NOT EXISTS uidx_position_permissions_position ON position_permissions (position)`).run();
  } catch {}

  // 2. Thêm cột mới vào users nếu chưa có
  const alterColumns = [
    "ALTER TABLE users ADD COLUMN employee_code text",
    "ALTER TABLE users ADD COLUMN position text",
    "ALTER TABLE users ADD COLUMN department text DEFAULT 'Vận hành 1' NOT NULL",
    "ALTER TABLE users ADD COLUMN email_company text",
    "ALTER TABLE users ADD COLUMN email_work text",
    "ALTER TABLE users ADD COLUMN phone text",
    "ALTER TABLE users ADD COLUMN status text DEFAULT 'active' NOT NULL",
  ];
  for (const sql of alterColumns) {
    try {
      await rawDb.prepare(sql).run();
    } catch {}
  }

  // 3. Khởi tạo 25 Cương vị mặc định
  let positionsSeeded = 0;
  for (const pos of DEFAULT_POSITIONS) {
    try {
      const existing = await rawDb.prepare("SELECT id FROM position_permissions WHERE position = ?").bind(pos.position).first();
      if (!existing) {
        await rawDb.prepare(
          "INSERT INTO position_permissions (position, role, permissions, description) VALUES (?, ?, ?, ?)"
        ).bind(pos.position, pos.role, JSON.stringify(pos.permissions), pos.description).run();
        positionsSeeded++;
      }
    } catch {}
  }

  // 4. Khởi tạo 124 Người dùng
  let usersSeeded = 0;
  for (const u of INITIAL_USERS) {
    const cleanUsername = u.username.trim().toLowerCase();
    try {
      const existing = await rawDb.prepare("SELECT id FROM users WHERE LOWER(username) = ?").bind(cleanUsername).first();
      const pHash = hashPassword(u.rawPassword);
      if (!existing) {
        await rawDb.prepare(
          "INSERT INTO users (username, password_hash, display_name, role, employee_code, position, department, email_company, email_work, phone, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
        ).bind(
          cleanUsername,
          pHash,
          u.displayName,
          u.role,
          u.employeeCode,
          u.position,
          u.department,
          u.emailCompany,
          u.emailWork,
          u.phone,
          u.status
        ).run();
        usersSeeded++;
      } else {
        // Cập nhật thông tin bổ sung nếu user đã tồn tại
        await rawDb.prepare(
          "UPDATE users SET employee_code = ?, position = ?, department = ?, email_company = ?, email_work = ?, role = ? WHERE LOWER(username) = ?"
        ).bind(
          u.employeeCode,
          u.position,
          u.department,
          u.emailCompany,
          u.emailWork,
          u.role,
          cleanUsername
        ).run();
      }
    } catch (e) {
      console.error(`Lỗi khi nạp user ${cleanUsername}:`, e);
    }
  }

  return { positionsSeeded, usersSeeded, totalUsers: INITIAL_USERS.length, totalPositions: DEFAULT_POSITIONS.length };
}
